from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow,QMessageBox
from PyQt5.QtCore import Qt
from PyQt5.QtGui import *
from PyQt5 import QtGui
import sys
def clear():
    if(len(line.text())!=0):
        line.clear()
    else:
        msg=QMessageBox(root)
        msg.setWindowTitle("Alert")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Input Widget is Empty")
        x = msg.exec_()
def action_7():
    text=line.text()
    line.setText(text + "7")
def action_8():
    text=line.text()
    line.setText(text + "8")
def action_9():
    text=line.text()
    line.setText(text + "9")
def action_1():
    text=line.text()
    line.setText(text + "1")
def action_2():
    text=line.text()
    line.setText(text + "2")
def action_3():
    text=line.text()
    line.setText(text + "3")
def action_4():
    text=line.text()
    line.setText(text + "4")
def action_5():
    text=line.text()
    line.setText(text + "5")
def action_6():
    text=line.text()
    line.setText(text + "6")
def action_0():
    text=line.text()
    line.setText(text + "0")
def action_plus():
    text=line.text()
    line.setText(text + "+")
def action_sub():
    text=line.text()
    line.setText(text + "-")
def action_mul():
    text=line.text()
    line.setText(text + "*")
def action_devid():
    text=line.text()
    line.setText(text + "/")
def action_dot():
    text=line.text()
    line.setText(text + ".")
def action_eval():
    if(len(line.text())!=0):
        val=line.text()
        line.clear()
        try:
            line.setText(str(eval(val)))
        except:
            line.setText("Invalid")
    else:
        msg=QMessageBox(root)
        msg.setWindowTitle("Alert")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Somthing Went Wrong")
        x = msg.exec_()
def action_del():
    val=line.text()
    s=""
    if(len(val)!=0):
        for i in range(len(val)-1):
            s+=val[i]
        line.setText(s)
    else:
        msg=QMessageBox(root)
        msg.setWindowTitle("Alert")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Input Widget is Empty")
        x = msg.exec_()
app=QApplication(sys.argv)
root=QMainWindow()
root.setWindowTitle("Simple-CalCulator")
root.setGeometry(400,400,306,240)
line=QtWidgets.QLineEdit(root)
line.move(13,10)
line.setAlignment(Qt.AlignRight)
line.setFixedWidth(280)
line.setStyleSheet("border:2px solid gray")
btnC=QtWidgets.QPushButton(root)
btnC.clicked.connect(clear)
btnC.setText("Clear")
btnC.setFixedSize(90,33)
btnC.move(13,42)
btnD=QtWidgets.QPushButton(root)
btnD.setText("Del")
btnD.setFixedSize(95,33)
btnD.move(110,42)
mul=QtWidgets.QPushButton(root)
mul.setText("*")
mul.setFixedSize(87,33)
mul.move(210,42)
btn7=QtWidgets.QPushButton(root)
btn7.setText("7")
btn7.setFixedSize(65,33)
btn7.move(13,78)
btn8=QtWidgets.QPushButton(root)
btn8.setText("8")
btn8.setFixedSize(65,33)
btn8.move(85,78)
btn9=QtWidgets.QPushButton(root)
btn9.setText("9")
btn9.setFixedSize(65,33)
btn9.move(155,78)
btn4=QtWidgets.QPushButton(root)
btn4.setText("4")
btn4.setFixedSize(65,35)
btn4.move(13,118)
btn5=QtWidgets.QPushButton(root)
btn5.setText("5")
btn5.setFixedSize(65,35)
btn5.move(85,118)
btn6=QtWidgets.QPushButton(root)
btn6.setText("6")
btn6.setFixedSize(65,35)
btn6.move(155,118)
add=QtWidgets.QPushButton(root)
add.setText("+")
add.setFixedSize(70,33)
add.move(224,78)
btn1=QtWidgets.QPushButton(root)
btn1.setText("1")
btn1.setFixedSize(65,35)
btn1.move(13,157)
btn2=QtWidgets.QPushButton(root)
btn2.setText("2")
btn2.setFixedSize(65,35)
btn2.move(85,157)
btn3=QtWidgets.QPushButton(root)
btn3.setText("3")
btn3.setFixedSize(65,35)
btn3.move(155,157)
sub=QtWidgets.QPushButton(root)
sub.setText("-")
sub.setFixedSize(70,35)
sub.move(224,118)
btn0=QtWidgets.QPushButton(root)
btn0.setText("0")
btn0.setFixedSize(65,35)
btn0.move(13,200)
dot=QtWidgets.QPushButton(root)
dot.setText(".")
dot.setFixedSize(65,35)
dot.move(85,200)
devid=QtWidgets.QPushButton(root)
devid.setText("/")
devid.setFixedSize(65,35)
devid.move(155,200)
eql=QtWidgets.QPushButton(root)
eql.setText("=")
eql.setFixedSize(70,80)
eql.setStyleSheet("background:dodgerblue;border:2px solid white;color:white")
eql.move(224,155)
btnD.clicked.connect(action_del)
btn7.clicked.connect(action_7)
btn8.clicked.connect(action_8)
btn9.clicked.connect(action_9)
btn4.clicked.connect(action_4)
btn5.clicked.connect(action_5)
btn6.clicked.connect(action_6)
btn1.clicked.connect(action_1)
btn2.clicked.connect(action_2)
btn3.clicked.connect(action_3)
btn0.clicked.connect(action_0)
devid.clicked.connect(action_devid)
add.clicked.connect(action_plus)
sub.clicked.connect(action_sub)
mul.clicked.connect(action_mul)
dot.clicked.connect(action_dot)
eql.clicked.connect(action_eval)
root.show()
sys.exit(app.exec_())